### ISSUE TITLE
With the correct setup I get the error "Data directory is required"

### ISSUE THREAD

**Issue by SelfDevTV** [victorteokw/seedgoose#11]
Hi,

first of all: Awesome library. 
I think I'm very close.

I have my data setup like this:

![2019-06-19 23_41_37- seedgooserc js (deleted) - forum-creator - Visual Studio Code](https://user-images.githubusercontent.com/48333000/59803469-d204a380-92eb-11e9-98b3-cc3cc9c4331f.png)

When I navigate into this folder (`seeder`) with the terminal and type `seedgoose seed` I get the error:

> (node:612) UnhandledPromiseRejectionWarning: Error: Data directory is required.

Full error message:

![2019-06-19 23_42_48-Window](https://user-images.githubusercontent.com/48333000/59803514-f82a4380-92eb-11e9-92bd-b059a8abae95.png)

What may cause the error. My `.seedgooserc.js` looks like this:

```
module.exports = {
  modelBaseDirectory: 'models',
  models: '*.js',
  data: 'data',
  db: 'mongodb://localhost:27017/testsuite1'
};
```

My `forums.js` file from the `data` folder looks like this:

```
module.exports = {
  _id: 'forumA',
  title: 'test',
  subForums: ['subA', 'subB', 'subC']
};
```

**So everything set up correctly according to the docs, or am I missing something? Why do I get the error every time?**

Thanks

**Comment by zhangkaiyulw** [comment]
Hi @SelfDevTV, I’ll look at this later today. I’m outside right now.

Thanks for using this.

**Comment by SelfDevTV** [comment]
@zhangkaiyulw Alright thank you!

**Comment by zhangkaiyulw** [comment]
Hi @SelfDevTV can you try 2.0 to see if this problem has been fixed?

**Comment by NickDjukic** [comment]
Hey there, I'm getting the same error with correct setup. Let me know if there was a fix

**Comment by micahelriceio** [comment]
I was also experiencing this error when using `.seedgooserc.js`, moving the config into `package.json` solved the issue for me ¯\_(ツ)_/¯

**Comment by Noah670** [comment]
I'm also having the same exact issue here

**Comment by Fambam-EC** [comment]
Did anyone get a good fix for this?  I am getting same error

**Comment by jeanpielmago** [comment]
seedgoose still works? @victorteokw

**Comment by Lilley-Peter** [comment]
I am having the same issue anyone figure this out?

**Comment by IvanVeridian** [comment]
I solved this error by creating a config file ( .seedgooserc.js) in the base directory and making sure the modelBaseDirectory was set correctly:
// .seedgooserc.js
module.exports = {
  modelBaseDirectory: 'app_server/models', // model directory name
  models: '**/*.js', // model matcher
  data: 'data', // data directory name
  db: 'mongodb://localhost:27017/DB-URL' // db connection url
};
